Repository armory-plugins/pluginRepository, pull requests merged in 2022-06, with the labels that each got.

#17 Release Armory.ArmoryHeader v0.1.0
  plugins.json
Labels: Armory.ArmoryHeader-v0.1.0

#18 Release Armory.ArmoryHeader v0.0.4
  plugins.json
Labels: Armory.ArmoryHeader-v0.0.4

#19 Release Armory.PolicyEngine 0.2.2
  plugins.json
Labels: Armory.PolicyEngine-0.2.2
